name: Compile LaTeX to PDF

on:
  push:
    paths:
      - '**.tex'
  pull_request:
    paths:
      - '**.tex'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"
      
      - name: Upload compiled PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ./**/*.pdf